### ISSUE TITLE
add guild information

### ISSUE THREAD

**Issue by ScandalousMan** [pikax/swgoh#14]
Hello,

First of all, thanks a lot for the awesome work you did with this package ! :D
I believe it could be very usefull to have at least guild PG coming back from swgoh.guild method.

What do you think ?

Have a great day,

Adrien

**Comment by pikax** [comment]
just update to **0.6.0**

you can get guild info and users with: https://runkit.com/embed/p10l0fm71sj4
it returns: 
``` typescript

export interface Guild {
    name: string,
    imageSrc: string;
    description: string;
    galacticPower: number,
    averageGalacticPower: number;
    rank: string;
    raidPoints: number;
    arenaRank: number;
    memberCount: number;
    profileCount: number;
    lastUpdated: Date;
    
    users: Array<{
        username: string,
        description: string,

        galacticPower: number,
        collectionScore: number;
        arenaRank?: number;
        arenaAverage: number;
    }>,
}
```


Hope that helps :)
