### ISSUE TITLE
Profile Data undefined

### ISSUE THREAD

**Issue by rmgirardin** [pikax/swgoh#2]
For users that don't have ally codes on swgoh.gg, the `joined` field is being bumped up to `allyCode`.
<img width="704" alt="screen shot 2017-09-13 at 5 31 08 pm" src="https://user-images.githubusercontent.com/19332184/30401815-877e6bf4-98a9-11e7-8a5e-8ade4c52a2b1.png">

**Comment by pikax** [comment]
Thank you, just fixed, update package to **0.1.3**
