### ISSUE TITLE
Ships stars

### ISSUE THREAD

**Issue by mARiote** [pikax/swgoh#3]
When the ship has 7 stars is parsed as 0*:
`   {
      "code": "slave-i",
      "description": "Slave I",
      "imageSrc": "//swgoh.gg/static/img/assets/tex.charui_slave1.png",
      "star": 0,
      "level": 85,
      "crew": [
        {
          "code": "boba-fett",
          "description": "Boba Fett",
          "imageSrc": "swgoh.gg/static/img/assets/tex.charui_bobafett.png",
          "star": 7,
          "level": 85
        }
      ],
      "galacticPower": 36946,
      "maxGalacticPower": 49949
    },`

**Comment by pikax** [comment]
fixed on v0.2.1

**Comment by pikax** [comment]
fixed on v0.2.1
